### ISSUE TITLE
Criação do processo de Login através do Tomcat 8

### ISSUE THREAD

**Issue by aannddrree** [evertongodoy/studio-pilates#2]

**Comment by evertongodoy** [comment]
Servlet configuração do tomcat efetuadas.

tomcat/server.xml

Realm:

<Realm className="org.apache.catalina.realm.JDBCRealm" connectionName="root" connectionPassword="mysql" connectionURL="jdbc:mysql://localhost:3306/pilates_schema" driverName="com.mysql.jdbc.Driver" roleNameCol="rolename" userCredCol="password" userNameCol="username" userRoleTable="usuarios" userTable="roles_usuarios"/>
